var tipuesearch = {"pages": [
     {"title": "Introducing The Cloudify Player", "text": "This Monday we’re launching the Cloudify online recipe catalog and the Cloudify Player, an embeddable, simple to use JavaScript widget that allows users to launch any Cloudify recipe on the cloud from within any web page, with a single click. The idea behind it is simple: visit a web page,...", "tags": "JavaScript", "loc": "http://www.cloudifysource.org/2013/05/15/introducing_the_cloudify_player.html"},
     {"title": "Using the Cloudify Player as an Open Source Framework for Building Your Own Cloud Application Marketplace on OpenStack", "text": "In the previous post, I outlined the main lessons learned from the Amazon Cloud Marketplace and suggested an alternative approach for building an open marketplace. In this post I’ll refer to a specific implementation of that alternative approach through a new Cloudify Service called the Cloudify Player. Introduction to the...", "tags": "JavaScript", "loc": "http://www.cloudifysource.org/2013/05/13/using_the_cloudify_player_as_an_open_source_framework_for_building_your_own_cloud_application_marketplace_on_openstack.html"},
     {"title": "Cross-Cloud Storage", "text": "Preface I am still amazed from time to time to find that even very intelligent people who know a lot about software development, but nothing about cloud computing, don’t seem to know this truth about the cloud “world”: when a machine (VM) goes down, its data is gone forever, unless...", "tags": "", "loc": "http://www.cloudifysource.org/2013/05/01/cross_cloud_storage.html"},
     {"title": "How to Install MySQL on any Cloud", "text": "This recipe enables users to install MySQL on any cloud in two modes: standalone and master-slave. In addition, after installing the MySQL service you can then take advantage of Cloudify's custom commands mechanism in", "tags": "", "loc": "http://www.cloudifysource.org/cloudifysourcetv#6Li_lCZXaKY"},     
     {"title": "Industry Event: Cloud World Forum London", "text": "The Cloudify Team will be on the ground at this year’s Cloud World Forum. Come stop by the booth to hear about updates and what’s new in Cloudify. The team has been invited to participate on a panel with other industry experts in the Cloud Computing arena. Details of the panel will be posted shortly.", "tags": "", "loc": "http://www.cloudwf.com/"},
     
]};



