var guide = {
	'2.1':{
		'bootstrapping':{
			'bootstrapping_azure':true,
			'bootstrapping_byon':true,
			'bootstrapping_ec2':true,
			'bootstrapping_hp':true,
			'bootstrapping_localcloud':true,
			'bootstrapping_process':true,
			'bootstrapping_rsopenstack':true
		},
		'clouddrivers':{
			'cloud_driver':true,
			'developing_custom_clouddriver':true,
			'tutorial_maven':true
		},
		'contribute':{
			'how_to':true
		},
		'deploying':{
			'deploying_apps':true,
			'deploying_azure':true,
			'troubleshoot_app':true
		},
		'developing':{
			'application_recipe':true,
			'attributes_api':true,
			'configuring_ui_section':true,
			'custom_commands':true,
			'extending_recipes':true,
			'lifecycle_events':true,
			'plugins':true,
			'recipes_overview':true,
			'recipe_parameters':true,
			'scaling_rules':true,
			'service_recipe':true,
			'sla_requirements':true,
			'the_service_context_api':true
		},
		'examples':{
			'ant_examples':true,
			'file_examples':true
		},
		'faq':{
			'faq':true
		},
		'integrations':{
			'chef_tutorial':true,
			'cloudify_chef_lifecycle_event_handlers':true
		},
		'monitoring':{
			'monitoring_app_post_deploy':true,
			'the_web_management_console':true
		},
		'overview':{
			'cloudify_intro':true,
			'cloud_driver_overview':true,
			'universal_service_manager':true
		},
		'plugins_and_probes':{
			'develop_your_plugin':true,
			'probes':true
		},
		'qsg':{
			'quick_start_guide':true,
			'quick_start_guide_2_1_1-m2':true,
			'quick_start_guide_apache':true,
			'quick_start_guide_ec2':true,
			'quick_start_guide_ec2_2_1_1-m2':true
		},
		'recipe':{
			'app_recipe_ref':true,
			'command_line_reference':true,
			'service_recipe_ref':true
		},
		'release_notes':{
			'release_notes':true
		},
		'setup':{
			'cloudify_prerequisites':true,
			'configuring_azure':true,
			'configuring_byon':true,
			'configuring_ec2':true,
			'configuring_openstack':true,
			'configuring_rsopenstack':true,
			'installing_the_cloudify_client':true,
			'post_installation_configuration':true
		},
		'test':{
			'easy_slider':true,
			'overview':true,
			'petclinic_deepdive':true,
			'tamir':true,
			'yaron':true
		},
		'undeploying':{
			'undeploy_apps':true,
			'undeploy_azure':true
		},
	},
	'2.2':{
		'bootstrapping':{
			'bootstrapping_azure':true,
			'bootstrapping_byon':true,
			'bootstrapping_cloud':true,
			'bootstrapping_ec2':true,
			'bootstrapping_hp':true,
			'bootstrapping_localcloud':true,
			'bootstrapping_process':true,
			'bootstrapping_rsopenstack':true,
			'bootstrapping_validations':true
		},
		'clouddrivers':{
			'cloud_driver':true,
			'developing_custom_clouddriver':true,
			'tutorial_maven':true
		},
		'common_patterns':{
			'file_examples':true
		},
		'contribute':{
			'how_to':true
		},
		'deploying':{
			'deploying_apps':true,
			'deploying_srvs':true,
			'troubleshoot_app':true
		},
		'developing':{
			'application_recipe':true,
			'attributes_api':true,
			'configuring_ui_section':true,
			'custom_commands':true,
			'extending_recipes':true,
			'lifecycle_events':true,
			'plugins':true,
			'recipes_overview':true,
			'recipe_parameters':true,
			'scaling_rules':true,
			'service_recipe':true,
			'sla_requirements':true,
			'the_service_context_api':true
		},
		'faq':{
			'faq':true
		},
		'integrations':{
			'chef_documentation':true,
			'chef_tutorial':true,
			'cloudify_chef_lifecycle_event_handlers':true
		},
		'monitoring':{
			'monitoring_app_post_deploy':true,
			'the_web_management_console':true
		},
		'overview':{
			'cloudify_intro':true,
			'cloud_driver_overview':true,
			'universal_service_manager':true
		},
		'plugins_and_probes':{
			'develop_your_plugin':true,
			'probes':true
		},
		'qsg':{
			'quick_start_guide':true,
			'quick_start_guide_apache':true,
			'quick_start_guide_ec2':true,
			'quick_start_guide_helloworld':true
		},
		'recipe':{
			'app_recipe_ref':true,
			'cloud_driver_config_ref':true,
			'command_line_reference':true,
			'service_recipe_ref':true
		},
		'release_notes':{
			'release_notes':true
		},
		'restapi':{
		},
		'rest_api':{
			'rest_api_attributes':true
		},
		'setup':{
			'cloudify_prerequisites':true,
			'configuring_azure':true,
			'configuring_byon':true,
			'configuring_ec2':true,
			'configuring_openstack':true,
			'configuring_rsopenstack':true,
			'installing_the_cloudify_client':true,
			'post_installation_configuration':true
		},
		'test':{
			'easy_slider':true,
			'overview':true,
			'petclinic_deepdive':true,
			'tamir':true,
			'yaron':true
		},
		'undeploying':{
			'undeploy_apps':true,
			'undeploy_azure':true
		},
	},
	'2.3':{
		'bootstrapping':{
			'bootstrapping_azure':true,
			'bootstrapping_byon':true,
			'bootstrapping_cloud':true,
			'bootstrapping_ec2':true,
			'bootstrapping_hp':true,
			'bootstrapping_localcloud':true,
			'bootstrapping_openstack':true,
			'bootstrapping_process':true,
			'bootstrapping_rsopenstack':true,
			'bootstrapping_validations':true
		},
		'clouddrivers':{
			'cloud_driver':true,
			'developing_custom_clouddriver':true,
			'tutorial_maven':true
		},
		'common_patterns':{
			'file_examples':true
		},
		'contribute':{
			'how_to':true
		},
		'deploying':{
			'deploying_apps':true,
			'deploying_srvs':true,
			'troubleshoot_app':true
		},
		'developing':{
			'application_recipe':true,
			'attributes_api':true,
			'configuring_ui_section':true,
			'custom_commands':true,
			'debugger':true,
			'extending_recipes':true,
			'how_storage_works':true,
			'lifecycle_events':true,
			'plugins':true,
			'recipes_overview':true,
			'recipe_parameters':true,
			'scaling_rules':true,
			'service_recipe':true,
			'sla_requirements':true,
			'storage':true,
			'the_service_context_api':true
		},
		'faq':{
			'faq':true
		},
		'integrations':{
			'chef_documentation':true,
			'chef_tutorial':true,
			'cloudify_chef_lifecycle_event_handlers':true,
			'puppet_documentation':true
		},
		'monitoring':{
			'monitoring_app_post_deploy':true,
			'the_web_management_console':true
		},
		'overview':{
			'cloudify_intro':true,
			'cloud_driver_overview':true,
			'universal_service_manager':true
		},
		'plugins_and_probes':{
			'develop_your_plugin':true,
			'probes':true
		},
		'qsg':{
			'quick_start_guide':true,
			'quick_start_guide_apache':true,
			'quick_start_guide_ec2':true,
			'quick_start_guide_helloworld':true
		},
		'recipe':{
			'app_recipe_ref':true,
			'cloud_driver_config_ref':true,
			'command_line_reference':true,
			'service_recipe_ref':true
		},
		'release_notes':{
			'release_notes':true
		},
		'restapi':{
		},
		'rest_api':{
			'rest_api_attributes':true
		},
		'setup':{
			'cloudify_prerequisites':true,
			'cloudify_without_shell':true,
			'configuring_azure':true,
			'configuring_byon':true,
			'configuring_ec2':true,
			'configuring_hp':true,
			'configuring_openstack':true,
			'configuring_rsopenstack':true,
			'configuring_security':true,
			'installation_and_setup':true,
			'installing_the_cloudify_client':true,
			'post_installation_configuration':true,
			'recipes_tab':true
		},
		'test':{
			'easy_slider':true,
			'overview':true,
			'petclinic_deepdive':true,
			'tamir':true,
			'yaron':true
		},
		'undeploying':{
			'undeploy_apps':true,
			'undeploy_azure':true
		},
	},
	'2.5':{
		'bootstrapping':{
			'bootstrapping_azure':true,
			'bootstrapping_byon':true,
			'bootstrapping_cloud':true,
			'bootstrapping_ec2':true,
			'bootstrapping_hp':true,
			'bootstrapping_localcloud':true,
			'bootstrapping_openstack':true,
			'bootstrapping_process':true,
			'bootstrapping_rackspace':true,
			'bootstrapping_rsopenstack':true,
			'bootstrapping_validations':true
		},
		'clouddrivers':{
			'cloud_driver':true,
			'developing_custom_clouddriver':true,
			'tutorial_maven':true
		},
		'common_patterns':{
			'file_examples':true
		},
		'contribute':{
			'how_to':true
		},
		'deploying':{
			'deploying_apps':true,
			'deploying_srvs':true,
			'troubleshoot_app':true
		},
		'developing':{
			'application_recipe':true,
			'attributes_api':true,
			'configuring_ui_section':true,
			'custom_commands':true,
			'debugger':true,
			'extending_recipes':true,
			'how_storage_works':true,
			'lifecycle_events':true,
			'plugins':true,
			'recipes_overview':true,
			'recipe_parameters':true,
			'scaling_rules':true,
			'service_recipe':true,
			'sla_requirements':true,
			'storage':true,
			'the_service_context_api':true
		},
		'faq':{
			'faq':true
		},
		'integrations':{
			'chef_documentation':true,
			'chef_tutorial':true,
			'cloudify_chef_lifecycle_event_handlers':true,
			'puppet_documentation':true
		},
		'monitoring':{
			'monitoring_app_post_deploy':true,
			'the_web_management_console':true
		},
		'overview':{
			'cloudify_intro':true,
			'cloud_driver_overview':true,
			'universal_service_manager':true
		},
		'plugins_and_probes':{
			'develop_your_plugin':true,
			'probes':true
		},
		'qsg':{
			'quick_start_guide':true,
			'quick_start_guide_apache':true,
			'quick_start_guide_ec2':true,
			'quick_start_guide_helloworld':true
		},
		'recipe':{
			'app_recipe_ref':true,
			'cloud_driver_config_ref':true,
			'command_line_reference':true,
			'service_recipe_ref':true
		},
		'release_notes':{
			'release_notes':true
		},
		'restapi':{
		},
		'rest_api':{
			'rest_api_attributes':true
		},
		'setup':{
			'cloudify_prerequisites':true,
			'cloudify_without_shell':true,
			'configuring_azure':true,
			'configuring_byon':true,
			'configuring_ec2':true,
			'configuring_hp':true,
			'configuring_openstack':true,
			'configuring_rackspace':true,
			'configuring_rsopenstack':true,
			'configuring_security':true,
			'installation_and_setup':true,
			'installing_the_cloudify_client':true,
			'post_installation_configuration':true,
			'recipes_tab':true
		},
		'test':{
			'easy_slider':true,
			'overview':true,
			'petclinic_deepdive':true,
			'tamir':true,
			'yaron':true
		},
		'undeploying':{
			'undeploy_apps':true,
			'undeploy_azure':true
		},
	},
	'2.6':{
		'bootstrapping':{
			'bootstrapping_azure':true,
			'bootstrapping_byon':true,
			'bootstrapping_cloud':true,
			'bootstrapping_ec2':true,
			'bootstrapping_hp':true,
			'bootstrapping_localcloud':true,
			'bootstrapping_openstack':true,
			'bootstrapping_process':true,
			'bootstrapping_rackspace':true,
			'bootstrapping_rsopenstack':true,
			'bootstrapping_validations':true,
			'configuring_large_scale_deployments':true
		},
		'clouddrivers':{
			'cloud_driver':true,
			'developing_custom_clouddriver':true,
			'tutorial_maven':true
		},
		'common_patterns':{
			'file_examples':true
		},
		'contribute':{
			'how_to':true
		},
		'deploying':{
			'deploying_apps':true,
			'deploying_srvs':true,
			'downtime_for_maintenance':true,
			'troubleshoot_app':true
		},
		'developing':{
			'application_recipe':true,
			'attributes_api':true,
			'best_practices_for_debugging_and_developing_recipes':true,
			'configuring_ui_section':true,
			'custom_commands':true,
			'debugger':true,
			'extending_recipes':true,
			'how_storage_works':true,
			'lifecycle_events':true,
			'maintenance_mode':true,
			'plugins':true,
			'recipes_overview':true,
			'recipe_parameters':true,
			'scaling_rules':true,
			'service_recipe':true,
			'sla_requirements':true,
			'storage':true,
			'the_service_context_api':true
		},
		'faq':{
			'faq':true
		},
		'integrations':{
			'chef_documentation':true,
			'chef_tutorial':true,
			'cloudify_chef_lifecycle_event_handlers':true,
			'puppet_documentation':true
		},
		'monitoring':{
			'monitoring_app_post_deploy':true,
			'the_web_management_console':true
		},
		'overview':{
			'cloudify_intro':true,
			'cloud_driver_overview':true,
			'universal_service_manager':true
		},
		'plugins_and_probes':{
			'develop_your_plugin':true,
			'probes':true
		},
		'qsg':{
			'qsg':true,
			'quick_start_guide':true,
			'quick_start_guide_apache':true,
			'quick_start_guide_ec2':true,
			'quick_start_guide_helloworld':true
		},
		'recipe':{
			'app_recipe_ref':true,
			'cloud_driver_config_ref':true,
			'command_line_reference':true,
			'service_recipe_ref':true
		},
		'release_notes':{
			'release_notes':true
		},
		'restapi':{
		},
		'rest_api':{
			'rest_api_attributes':true
		},
		'setup':{
			'cloudify_prerequisites':true,
			'cloudify_without_shell':true,
			'configuring_azure':true,
			'configuring_byon':true,
			'configuring_ec2':true,
			'configuring_hp':true,
			'configuring_openstack':true,
			'configuring_rackspace':true,
			'configuring_rsopenstack':true,
			'configuring_security':true,
			'installation_and_setup':true,
			'installing_the_cloudify_client':true,
			'post_installation_configuration':true,
			'recipes_tab':true
		},
		'test':{
			'easy_slider':true,
			'overview':true,
			'petclinic_deepdive':true,
			'tamir':true,
			'yaron':true
		},
		'undeploying':{
			'undeploy_apps':true,
			'undeploy_azure':true
		},
	},
	'2.7':{
		'bootstrapping':{
			'bootstrapping_azure':true,
			'bootstrapping_byon':true,
			'bootstrapping_cloud':true,
			'bootstrapping_cloudstack':true,
			'bootstrapping_ec2':true,
			'bootstrapping_hp':true,
			'bootstrapping_localcloud':true,
			'bootstrapping_openstack':true,
			'bootstrapping_process':true,
			'bootstrapping_rackspace':true,
			'bootstrapping_rsopenstack':true,
			'bootstrapping_validations':true,
			'configuring_large_scale_deployments':true
		},
		'clouddrivers':{
			'bootstrap_and_deployment_drill_down':true,
			'cloud_driver':true,
			'developing_custom_clouddriver':true,
			'network':true,
			'tutorial_maven':true
		},
		'common_patterns':{
			'file_examples':true
		},
		'contribute':{
			'how_to':true
		},
		'deploying':{
			'deploying_apps':true,
			'deploying_srvs':true,
			'troubleshoot_app':true
		},
		'developing':{
			'application_recipe':true,
			'attributes_api':true,
			'best_practices_for_debugging_and_developing_recipes':true,
			'configuring_ui_section':true,
			'custom_commands':true,
			'debugger':true,
			'extending_recipes':true,
			'how_storage_works':true,
			'lifecycle_events':true,
			'maintenance_mode':true,
			'plugins':true,
			'recipes_overview':true,
			'recipe_parameters':true,
			'scaling_rules':true,
			'service_recipe':true,
			'sla_requirements':true,
			'storage':true,
			'the_service_context_api':true
		},
		'faq':{
			'faq':true
		},
		'integrations':{
			'chef_documentation':true,
			'chef_tutorial':true,
			'cloudify_chef_lifecycle_event_handlers':true,
			'puppet_documentation':true
		},
		'monitoring':{
			'monitoring_app_post_deploy':true,
			'the_web_management_console':true
		},
		'overview':{
			'cloudify_intro':true,
			'cloud_driver_overview':true,
			'universal_service_manager':true
		},
		'plugins_and_probes':{
			'develop_your_plugin':true,
			'probes':true
		},
		'qsg':{
			'qsg':true,
			'quick_start_guide':true,
			'quick_start_guide_apache':true,
			'quick_start_guide_ec2':true,
			'quick_start_guide_helloworld':true
		},
		'recipe':{
			'app_recipe_ref':true,
			'cloud_driver_config_ref':true,
			'command_line_reference':true,
			'service_recipe_ref':true
		},
		'release_notes':{
			'release_notes':true
		},
		'restapi':{
		},
		'rest_api':{
			'rest_api_attributes':true
		},
		'setup':{
			'cloudify_prerequisites':true,
			'cloudify_without_shell':true,
			'configuring_azure':true,
			'configuring_byon':true,
			'configuring_cloudstack':true,
			'configuring_ec2':true,
			'configuring_hp':true,
			'configuring_openstack':true,
			'configuring_rackspace':true,
			'configuring_rsopenstack':true,
			'configuring_security':true,
			'installation_and_setup':true,
			'installing_the_cloudify_client':true,
			'post_installation_configuration':true,
			'recipes_tab':true
		},
		'test':{
			'easy_slider':true,
			'overview':true,
			'petclinic_deepdive':true,
			'tamir':true,
			'yaron':true
		},
		'undeploying':{
			'undeploy_apps':true,
			'undeploy_azure':true
		},
	}
};